// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdHBQF13ysL7migJ7OpfQlaNfWFVGM7PU',
    appId: '1:1060527413509:web:7da8d76cb07211d0783f6c',
    messagingSenderId: '1060527413509',
    projectId: 'fir-flutter-codelab-52293',
    authDomain: 'fir-flutter-codelab-52293.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-52293.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleLAAEDr748Q35S4zqgca1SU9jl6aC68',
    appId: '1:1060527413509:android:8196db2c8d7c75be783f6c',
    messagingSenderId: '1060527413509',
    projectId: 'fir-flutter-codelab-52293',
    storageBucket: 'fir-flutter-codelab-52293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeACsbHGTuocZB9RdK077b6qc7dyy44Y',
    appId: '1:1060527413509:ios:9f0490c3ca3a9648783f6c',
    messagingSenderId: '1060527413509',
    projectId: 'fir-flutter-codelab-52293',
    storageBucket: 'fir-flutter-codelab-52293.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQeACsbHGTuocZB9RdK077b6qc7dyy44Y',
    appId: '1:1060527413509:ios:9f0490c3ca3a9648783f6c',
    messagingSenderId: '1060527413509',
    projectId: 'fir-flutter-codelab-52293',
    storageBucket: 'fir-flutter-codelab-52293.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdHBQF13ysL7migJ7OpfQlaNfWFVGM7PU',
    appId: '1:1060527413509:web:d0b5dd34dddf000b783f6c',
    messagingSenderId: '1060527413509',
    projectId: 'fir-flutter-codelab-52293',
    authDomain: 'fir-flutter-codelab-52293.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-52293.appspot.com',
  );
}
